### ISSUE TITLE
`Series[int]` instead of `Series[bool]` for masks combined with binary operators

### ISSUE THREAD

**Issue by thilobro** [pandas-dev/pandas-stubs#380]
**Describe the bug**
When combining masks with a binary operator (e.g. &), the returned type is `Series[int]` instead of `Series[bool]`. This means `mypy` complains if you use the mask for indexing.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
```
import pandas as pd

df = pd.dataframe({"a": [1, 2, 3, 4, 5]})
mask = (df["a"] < 4) & (df["a"] > 2)
print(df[mask])
```
3. Indicate which type checker you are using (`mypy` or  `pyright`).
`mypy --strict`
4. Show the error message received from that type checker while checking your example.
```
bug.py:5: error: Invalid index type "Series[int]" for "DataFrame"; expected type "Union[Tuple[Any, ...], Series[bool], DataFrame, List[str], Index, ndarray[Any, dtype[str_]], ndarray[Any, dtype[bool_]], Sequence[Tuple[Union[str, bytes, date, datetime, timedelta, bool, int, float, complex, Timestamp, Timedelta], ...]]]"
Found 1 error in 1 file (checked 1 source file)
```

**Please complete the following information:**
 - OS: Ubuntu 20.04
 - python version 3.8.10
 - version of type checker: mypy 0.982
 - version of installed `pandas-stubs`: 1.5.0.221010

**Comment by thilobro** [comment]
The workaround I currently use is:
`df[mask.astype(bool)]`

**Comment by Dr-Irv** [comment]
This was introduced in #378 .  

We need to differentiate between `pd.Series([1,2,3,4], dtype=int) & 3` and `pd.Series([True, False, True], dtype=bool) &  (pd.Series([1,2,3]) > 2)`

The former produces `Series[int]`, the latter produces `Series[bool]`, so we have to introduce appropriate overloads for `__and__()`, `__or__()`, `__xor__()` and the reverse operators as well based on whether booleans or ints are passed.

You could go back to version 1.5.0.221003 and your code will work, but we should fix this.
